steps:
  - name: 'node:18.12.0-alpine'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'
  - name: 'node:18.12.0-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
  - name: 'maven:3.8.6-jdk-17-alpine'
    entrypoint: 'mvn'
    args: ['package']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy']