runtime: java17
instance_class: F2

env_variables:
  # Configuración de la base de datos MySQL en Cloud SQL
  SPRING_DATASOURCE_URL: jdbc:mysql://google/sprint3DB?cloudSqlInstance=ispp-2425-03:europe-west1:eventbrideserverdb&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&serverTimezone=Europe/Madrid&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  
  # Variables para WebSockets
  SPRING_WEBSOCKET_ENABLED: "true"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

handlers:
  # Configuración específica para WebSockets
  - url: /ws
    script: auto
    secure: always
    
  - url: /ws/.*
    script: auto
    secure: always
    
  - url: /ws/info
    script: auto
    secure: always

  # Serve all API calls to Spring
  - url: /api/.*
    script: auto

  # Serve calls to Swagger-UI
  - url: /v3/api-docs.*
    script: auto
  - url: /swagger-ui.*
    script: auto

  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*\..+)$

  # Catch all handler to index.html
  - url: /.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

# Configuración de red necesaria para WebSockets
network:
  session_affinity: true
