name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # esto nos permite ejecutar manualmenete este orkflow por si hay problemas

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuración de JDK 17
      - name: Setup JDK 17 (si usas Java 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: ispp-eventbride  
          token: ${{ secrets.SONAR_TOKEN }}  # Token de SonarCloud en los secretos de GitHub
