name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # esto nos permite ejecutar manualmente este workflow por si hay problemas

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuración de JDK 17
      - name: Setup JDK 17 (si usas Java 17)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Compilar el proyecto sin ejecutar tests
      - name: Build with Maven (skip tests)
        run: mvn clean verify -DskipTests

      # Ejecutar el análisis con SonarCloud sin ejecutar tests
      - name: Analyze with SonarCloud (skip tests)
        run: |
          mvn sonar:sonar \
            -DskipTests \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=security-team-5 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=Security-Team-5_Eventbride

      - name: Instalar sonar-report CLI
        run: npm install -g sonar-report

      - name: Generar reporte JSON desde SonarCloud
        run: |
          sonar-report \
            --sonarurl="https://sonarcloud.io" \
            --sonarcomponent="Security-Team-5_Eventbride" \
            --sonarorganization="security-team-5" \
            --project="EventBride" \
            --application="eventbride" \
            --release="1.0.0" \
            --branch="master" \
            --save-report-json \
            --output="sonar-report.json"

      - name: Subir reporte a DefectDojo (Soprasteria Scan)
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
            -F "scan_type=Soprasteria SonarQube Scan" \
            -F "file=@sonar-report.json"
