name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # esto nos permite ejecutar manualmente este workflow por si hay problemas

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuración de JDK 17
      - name: Setup JDK 17 (si usas Java 17)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Compilar el proyecto sin ejecutar tests
      - name: Build with Maven (skip tests)
        run: mvn clean verify -DskipTests

      # Ejecutar el análisis con SonarCloud sin ejecutar tests
      - name: Analyze with SonarCloud (skip tests)
        run: |
          mvn sonar:sonar \
            -DskipTests \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=ispp-eventbride \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=ISPP-Eventbride_Eventbride
