name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # esto nos permite ejecutar manualmenete este orkflow por si hay problemas

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuración de JDK 17
      - name: Setup JDK 17 (si usas Java 17)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Paso opcional: Si quieres primero compilar y probar 
      # en un paso separado (mvn clean verify):
      - name: Build and test with Maven
        run: mvn clean verify

      # Paso para ejecutar el análisis con Sonar
      - name: Analyze with SonarCloud
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@v1
#        with:
#          # Si necesitas enviar argumentos adicionales al scanner:
#          args: >
#            -Dsonar.organization=ispp-eventbride 
#            -Dsonar.projectKey=ISPP-Eventbride_Eventbride
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}